name: firebase_windows_example
description: Demonstrates how to use the firebase_windows plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.2
  firebase_windows:
    path: ../
  mime: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
