name: firebase_windows_example
description: Demonstrates how to use the firebase_windows plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_windows:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
