name: firebase_windows
description: Windows implementations of the Firebase Flutter plugin for Flutter apps.
version: 0.0.7
homepage: https://github.com/DeepHow/App-FirebaseWindows/

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.0.0
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  pigeon: ^9.2.5

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FirebaseWindowsPluginCApi
